---
# Source: take-the-helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-take-the-helm
  labels:
    helm.sh/chart: take-the-helm-0.1.0
    app.kubernetes.io/name: take-the-helm
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: take-the-helm
      app.kubernetes.io/instance: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: take-the-helm
        app.kubernetes.io/instance: app
    spec:
      serviceAccountName: app-take-the-helm
      securityContext:
        {}
      containers:
        - name: take-the-helm
          securityContext:
            {}
          image: "dsaidgovsg/lnd:take-the-helm-0.1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
